-- ============================================
-- MIGRATION: Tutorial content + completion state
-- Stores tutorial content as a single JSON document and tracks whether a user
-- has completed the tutorial.
-- ============================================

alter table public.profiles
  add column tutorial_completed_at timestamp with time zone;

grant update (username, get_notifications, tutorial_completed_at, updated_at)
on table public.profiles
to authenticated;

create table "public"."tutorial_content" (
  "id" bigint generated by default as identity not null,
  "content" jsonb not null,
  "created_at" timestamp with time zone not null default now(),
  "updated_at" timestamp with time zone not null default now()
);

alter table "public"."tutorial_content" enable row level security;

create unique index tutorial_content_pkey
  on public.tutorial_content using btree (id);

alter table "public"."tutorial_content"
  add constraint "tutorial_content_pkey"
  primary key using index "tutorial_content_pkey";

create policy "Tutorial content is viewable by everyone."
  on "public"."tutorial_content"
  as permissive
  for select
  to public
  using (true);

create policy "Only service role can insert tutorial content."
  on "public"."tutorial_content"
  as permissive
  for insert
  to service_role
  with check (true);

create policy "Only service role can update tutorial content."
  on "public"."tutorial_content"
  as permissive
  for update
  to service_role
  using (true);

create policy "Only service role can delete tutorial content."
  on "public"."tutorial_content"
  as permissive
  for delete
  to service_role
  using (true);

grant select on table "public"."tutorial_content" to "anon";
grant select on table "public"."tutorial_content" to "authenticated";
grant all on table "public"."tutorial_content" to "service_role";

create or replace function update_tutorial_content_updated_at()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger update_tutorial_content_updated_at_trigger
  before update on tutorial_content
  for each row
  execute function update_tutorial_content_updated_at();
